name: Documentation
description: Add or update project documentation and related resources.
title: "docs: <description>"
labels: [documentation]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What needs to be investigated?
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional Information
      description: Provide any additional details, such as links, screenshots, etc.
    validations:
      required: false
